FROM python:2.7
MAINTAINER Fabio Montefuscolo <fabio.montefuscolo@hacklab.com.br>
MAINTAINER Moacir Moda <moa.moda@gmail.com>

RUN apt-get update \
    && apt-get install -y libpq-dev libjpeg-dev libpng12-dev gettext \
    && apt-get install -y npm vim \
    && apt-get install -y postgresql-client

RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install -g phantomjs-prebuilt bower

RUN mkdir -p /app

COPY . /app/timtec
RUN mkdir -p /app/webfiles/static \
   && mkdir -p /app/webfiles/media \
   && pip install -r /app/timtec/requirements/production.txt \
   && pip install -r /app/timtec/requirements/local.txt \
   && pip install -r /app/timtec/requirements/test.txt \

WORKDIR /app/timtec

RUN cd /app/timtec \
   && npm install \
   && node bower install \
   && node node_modules/grunt-cli/bin/grunt \
   && python /app/timtec/manage.py compilemessages

RUN export PYTHONPATH="/app/timtec:$PYTHONPATH"
EXPOSE 8000 8000

CMD ["python", "/app/timtec/manage.py", "runserver", "0.0.0.0:8000"]
