FROM debian:jessie
MAINTAINER Fabio Montefuscolo <fabio.montefuscolo@hacklab.com.br>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y python python-pip python-dev \
    && apt-get install -y libpq-dev libjpeg-dev libpng12-dev gettext \
    && apt-get install -y nginx supervisor \
    && apt-get install -y npm git vim \
    && apt-get install -y postgresql-client

RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install -g phantomjs-prebuilt bower

RUN useradd -m -d /app -u 1000 -s /bin/bash timtec
RUN mkdir -p /app

# Prefer to use mdillon/postgis
ENV DJANGO_DATABASE_URL='postgres://timtec:timtec@postgres/timtec'
ENV PYTHONPATH='/app/timtec'
ENV GUNICORN_LOG_LEVEL='info'
ENV GUNICORN_EXTRA_FLAGS=''
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV LANGUAGE=C.UTF-8  

COPY . /app/timtec
RUN mkdir -p /app/webfiles/static \
   && mkdir -p /app/webfiles/media \
   && pip install -r /app/timtec/requirements/production.txt \
   && chown -R timtec /app

WORKDIR /app/timtec
USER timtec

RUN npm install \
   && node bower install \
   && node node_modules/grunt-cli/bin/grunt \
   && python manage.py compilemessages

USER root
EXPOSE 8000 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
